### ISSUE TITLE
Resource namespace

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#10]
I found it a little bit confusing, as you could call the current stuff in the Api namespace resource as well. In fact, I would prefer that. Call this Model maybe?

**Comment by Nyholm** [comment]
👍

**Comment by Nyholm** [comment]
It also make more sense since we got a ModelDeserializer

**Comment by sagikazarmark** [comment]
I think we somehow skipped one part of this.

The proposed renamings here:

- Api -> Resource (skipped)
- Resource -> Model (done)

Actually Api is fine, since it contains the essential parts for the Api itself. Another approach would be to say Tweet and Stats are *Resources* of the Api, and as such they should be under the Resource namespace.

Both is fine for me, I can't really decide, so it's up to you.

**Comment by Nyholm** [comment]
I think all the endpoints should be under the API namespace. The model could be in the Model namespace (as they are). 

I do not believe that the endpoint should be in the Resource name space because "resource" is often  associated with javascripts, images, views and css.

**Comment by sagikazarmark** [comment]
> I do not believe that the endpoint should be in the Resource name space because "resource" is often associated with javascripts, images, views and css.

Well, this is a totally different context IMO, but as I said I am fine with both options.
