### ISSUE TITLE
ApiResponse interface

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#11]
What's the rationale behind? IMO the ApiClient/Resource knows the Model to use, doesn't it? In that case an extra interface does not really add anything, does it?

**Comment by Nyholm** [comment]
It does for the Deserializers.https://github.com/api-php/boilerplate/blob/master/src/Deserializer/ModelDeserializer.php#L39

**Comment by sagikazarmark** [comment]
Ah, missed that. Well, it looks a bit strange from a domain point of view. Wonder if we could get around this with duck typing.

In any case: call it Model?

**Comment by Nyholm** [comment]
Yes, Rename the namespace `Resource\Api` to `Model\Api`. 

What do you mean with "duck typing"?

**Comment by sagikazarmark** [comment]
Duck typing: check if there is a create method and it accepts an array instead of checking with an interface. Less elegant, but does not interfere with the domain. But it doesn't really matter after all. Any reason why it should be Model\Api instead of just Model?

**Comment by Nyholm** [comment]
Using duck typing is not type safe. We do not have the contract that is provided with the interface that makes sure that the `create` function accepts an array as first argument. 

> Any reason why it should be Model\Api instead of just Model?

What if we have other models in our client? But hm... what other models should that be? 

No, no real reason.
