### ISSUE TITLE
Place to set $apiKey or any credentials

### ISSUE THREAD

**Issue by Kwadz** [api-php/boilerplate#13]
Why is there two possibilities to set `$apiKey` (one in the `ApiClient` constructor, the other in `HttpClientConfigurator`)?
Currently it seems that if we want to set `$apiKey` with `HttpClientConfigurator`, it will be overwritten to null by the `ApiClient` constructor...

**Comment by sagikazarmark** [comment]
The ApiClient optionally takes an API key parameter. If it is null, the set method won't be called.
