### ISSUE TITLE
Remove PSR7 hydrator

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#14]
Although the Deserializer concept should probably cover all our cases, I feel returning the response object itself is exceptional, and later probably we might find some more cases where we need to make distinction between deserializing the request and just returning the response.

I already have one example: error handling. In this case I think we should not throw domain exceptions upon on-2xx status codes.

The only problem I can see is deserializer is already optional, and defaults to the ModelSerializer which seems to be fine. A possible solution would be to remove the typehint and allow false as value as well?

The point would be that we check every time if we have a deserializer (when necessary). If not, just return the response without any further domain/serialization logic.

Another option is that we leave the current deserializer in place, but in that case ALL other handling stuff needs to be part of the deserializer: formatting, domain exceptions (!), etc which is also not really good, since every request might have different errors for example. (A possible solution to this could be an aggregate deserializer which deserializes per model?)

**Comment by Nyholm** [comment]
I like the PSR-7 deserializer because it treats all responses equal. I understand however that there is an issue will error handling. But, if we are throwing an DomainException we would probably need the serializer as well to populate it with some data. 

Im not against the idea but I need some time to think.. 

-------------

Suggestion how to error handle:

```php

class SpecialApi {
  public function endpoint() {
    $psr7 = $this->httpGet('/foo');

    // Do some tests for normal stuff like 404, 403 and 500. This function will throw an exception
    $this->normalErrorHandle($psr7);
    if ($psr7->getStatusCode() === 417) {
       // Special error code for this endpoint
       throw ApiException::create($this->deserializer->deserialize($psr7, Error417Exception::class));
    }
 
    // Everything is green
    return $this->deserializer->deserialize($psr7, EndpointResponse::class);
  }
}
```
(Copying this comment to another PR)

**Comment by Nyholm** [comment]
Our exceptions should not depend on the hydrator. IE they will always have the same type of data in them. 

It does makes sense to remove the PSR-7 hydrator and allow the $hydrator to be `false`.

**Comment by sagikazarmark** [comment]
Rename it to NoopHydrator and set it to null in the constructor. Best idea so far
