### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#15]
Change from APIPHP to Api? or ApiPhp? I even thought about an imaginary name: API Factory or SDK Factory. 😄

**Comment by Nyholm** [comment]
I really do not like APIPHP. =)

But API Factory does not make sense for https://github.com/api-php/localise.biz/blob/master/src/LocoClient.php

`ApiPhp` is better. Or maybe do something completely different like `CommunityApiClient`

**Comment by sagikazarmark** [comment]
Well, ApiFactory is rather a vendor name, but ApiPhp works for me too.

**Comment by Nyholm** [comment]
`ClientFactory`?

**Comment by sagikazarmark** [comment]
That's too wide term IMO. What about SDK? That's what we basically do here, no matter they are all REST API clients.

**Comment by Nyholm** [comment]
So `ClientSDK`? That is too wide... Or it **feels** to wider.. =) 

(A) Either we go with something descriptive. ClientApi, CommunityApi, ApiPhp, ApiClient etc. 
(B) Or we do a organisation name like: Snappy, Fuzzy, FriendsOfSymfony, API friends etc. 

I kind of like ApiFactory to be honest. But we do not do API's we do API *clients*

**Comment by sagikazarmark** [comment]
In fact we DO APIs: API client is just an implementation, which is actually doing an API 😝 
But I agree, that this is not really a common thinking about APIs, so this might feel weird.

On the other hand: we are not limited to clients, although we mainly do them. I always wanted to set up some simple foundation for APIs. Or we can also have any kind of API helper tool we can imagine. From this point of view neither client nor SDK is a good choice.

FriendsOfAPI -> FOA sounds cool, even better: FAPI :trollface:

**Comment by Nyholm** [comment]
Im okey both FriendsOfApi, FOA and FAPI. 

So `Fapi\Boilerplate`?

**Comment by sagikazarmark** [comment]
Since it's an abbreviation, I would say FAPI\Boilerplate (see FOS), but Fapi works too, doesn't really matter after all. Will you rename the orga?

**Comment by Nyholm** [comment]
Good
