### ISSUE TITLE
File headers

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#16]
To be honest I am not really a fan of this anymore. I used to do it blindly following the symfony standard, but I think it's noise and doesn't have any added value. I have done some research back then and AFAIK it does not add any extra legal protection to an already quite permissive license.

WDYT?

**Comment by Nyholm** [comment]
Im happy to remove them, but I think it is a requirement for MIT. If it isn't I think we should remove them.

**Comment by sagikazarmark** [comment]
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

You mean this?

I have started to do another research, and this time I am unhappy about the result: http://lu.is/blog/2012/03/17/on-the-importance-of-per-file-license-information/

**Comment by sagikazarmark** [comment]
We keep them for legal reasons.
