### ISSUE TITLE
HttpClient builder

### ISSUE THREAD

**Issue by Nyholm** [api-php/boilerplate#2]
If an API has a lot of custom plugins. Like https://github.com/KnpLabs/php-github-api they need a client builder. What is the way to go here?

Also related is https://github.com/php-http/client-common/pull/40

We do not need to solve this now but it could be interesting to have in mind

**Comment by sagikazarmark** [comment]
Could it be a job for the client configurator? We can always wrap a client in a plugin client.

**Comment by Nyholm** [comment]
👍

**Comment by Nyholm** [comment]
Add a `prependPlugin`/`appendPlugin` function on the client configurator.
