### ISSUE TITLE
Domain model naming

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#26]
Our current domain models are not really meaningful. Wherever possible, we should rather return something like a boolean value if we want to reflect success. If we cannot return the "real" model (Tweet) we should use rather meaningful names, like TweetCreated, TweetDeleted, etc.

**Comment by Nyholm** [comment]
I agree with you. But I do not think it works in the general case. Or maybe it does. Picture this scenario: 

The API has two endpoints:
**www.fake-twitter.com/api/tweet/create**
```json
{
   "message": "Tweet created",
   "timestamp": "xxxx"
}
```

**www.fake-twitter.com/api/tweet/{id}/reply**
```json
{
   "message": "Reply created",
   "timestamp": "xxxx",
   "replied_to": "[id]"
}
```
.... Hm.. it does make sense if we have a TweetCreated and ReplyCreated. 

I guess what I **do not want** is to create is a model that is retured by multiple endpoints. Ie, I do not want a `Tweet` model to be returned for the endpoints above. That would make the `Tweet::$repliedTo` property optional for one request. 


-------------

👍
