### ISSUE TITLE
Write docs about why we should not use domain objects as parameters

### ISSUE THREAD

**Issue by Nyholm** [api-php/boilerplate#32]
* It is overhead
* It may conflict with the app. dev's domain object

We should do like github. Endpoints should take array or param + array. 
One could also create a builder to build this array. See Mailgun API

**Comment by Nyholm** [comment]
Related to #6

**Comment by Kwadz** [comment]
It seems this way does not allow to easily manage nested objects.

**Comment by Nyholm** [comment]
If you are using nested objects you should provide a builder for creating those parameters. 

//Tobias Nyholm
