### ISSUE TITLE
Use expectations

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#42]
How about using `assert` instead of this:

https://github.com/FriendsOfApi/boilerplate/blob/master/src/Api/Tweet.php#L56

Not sure if it's any better or not, would make sense to do some research. The SPL InvalidArgumentException is kind of redundant from this point of view.

**Comment by Nyholm** [comment]
👍  to use https://github.com/webmozart/assert

**Comment by sagikazarmark** [comment]
I like that package, but I wonder if we need it in this boilerplate. By assert I meant the language construct in PHP. For some is empty checks it should be more than enough IMO, more importantly, KISS.

**Comment by Nyholm** [comment]
Sure.

**Comment by sagikazarmark** [comment]
Just came across this: 

> Assertions should not be used for normal runtime operations like input parameter checks. As a rule of thumb your code should always be able to work correctly if assertion checking is not activated.

Maybe it's not really a good idea after all

**Comment by Nyholm** [comment]
With scalar type hints there is no much assertions to do, right?

**Comment by sagikazarmark** [comment]
Well, only the empty checks. Honestly I wonder why it's not recommended to use the above, but it's okay to use ifs.
