### ISSUE TITLE
Use HttpClient in ApiClient constructor

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#5]
I would create an `ApiClient::configure` method which accepts the current parameters and injects the HTTP client. Better in case someone configures a client himself.

**Comment by Kwadz** [comment]
Instead of the HttpClientConfigurator (which respect the single responsibility principle)? Or you suggest that `ApiClient::configure` use the HttpClientConfigurator?

**Comment by Nyholm** [comment]
That would risk  that the client does not get properly configured. How about doing the reverse?

```php
ApiClient::create(string $apiKey, HttpClient $httpClient)
```

**Comment by Nyholm** [comment]
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L141

**Comment by sagikazarmark** [comment]
> That would risk that the client does not get properly configured.

I don't see why. It's a matter of documentation IMO.

I prefer having the higher level layers in static factories and having the constructor accept the lower level arguments. It provides the maximum felxibility. It's also easier to logically follow in the object tree.

**Comment by Nyholm** [comment]
But in GitHub's case your arguments does not work. They need the builder/`HttpClientConfigurator` in the client to add/remove plugins as they go.

**Comment by sagikazarmark** [comment]
> They need the builder/HttpClientConfigurator in the client to add/remove plugins as they go.

They do it only in the constructor. We could do it in the static factory as well. As said, I think it's a matter of documentation. Also, if the client is a mandatory parameter in the constructor, there is no way that you accidentally create an API client, you MUST manually pass an HTTP Client as well. It's your responsibility to pass a properly configured one.

Not to mention integration testability: a mock client does not need all those plugins if you want to write integration tests for your code with the API client.

**Comment by Nyholm** [comment]
Making the HTTP client mandatory make sense. Im 👍 

Github uses the builder all over the place:
* https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L304
* https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L330

**Comment by sagikazarmark** [comment]
Well, I don't really like how Github does things with the builder. I don't see why modifying dependencies runtime (after instantiation) like cache makes sense. Apart from those, the Builder also caches the client, so upon the first access (if no changes are made) it will always return the same client. So why not do it once then?
