### ISSUE TITLE
Naming convention between Model and Api classes

### ISSUE THREAD

**Issue by Kwadz** [api-php/boilerplate#51]
Class names are the same for `FAPI\Boilerplate\Api\Tweet` and `FAPI\Boilerplate\Model\Tweet\Tweet`.

I understood same word should mean same thing:
![api-design](https://cloud.githubusercontent.com/assets/1472599/21574440/1c423846-cef3-11e6-87dd-adff4a61c83c.jpg)

Here the Tweet name can easily mean a Tweet in the model context. But what's about `FAPI\Boilerplate\Api\Tweet`? What is the role of this class? It's different and it has the same name.

How to avoid confusion?

**Comment by sagikazarmark** [comment]
Short answer: you can't always. In many cases you would have to use names with meta keywords in them (Collection, Model, Resource) which rarely fits into the models. Although in natural language you use them in parallel: "The List endpoint of Tweets [resource] returns [a collection of] Tweets" At least I haven't found a sane solution to this problem.

What I have in mind though is if the Api (Resource) classes should be plural or not (Tweet vs Tweets, like Stat vs Stats)

**Comment by Nyholm** [comment]
I think PHP classes and namespaces should always be in singular. But I have a hard time making singular of "stats". But to be consistent, we should do "stat". 

However, `ApiClient::stats()` is still okey. It is a function.

**Comment by sagikazarmark** [comment]
Not sure. API Resources are usually plural (Organizations, Users, etc) and I see a bit of inconsistency here.

**Comment by Nyholm** [comment]
Yeah. Rest endpoints should be in plural. But it does not mean that we have to use plural in our API classes. Or.. we decide to use plural and it will solve the question in #46

**Comment by sagikazarmark** [comment]
Well, I don't insist, Github API is inconsistent about this as well: https://github.com/KnpLabs/php-github-api/tree/master/lib/Github/Api

No, it wouldn't. We have a Tweets collection object.

**Comment by Nyholm** [comment]
I know they are inconsistent... 

If it does not solve #46 I would prefer that we always stick to singular with our PHP classes.
