### ISSUE TITLE
Serialize a domain object to the request body

### ISSUE THREAD

**Issue by Kwadz** [api-php/boilerplate#6]
What would be a clean way to serialize a domain object to the request body?

**Comment by Nyholm** [comment]
It depends on your API. Will the API take a json string? I would create a serializer or use SymfonySerializer component.

**Comment by Kwadz** [comment]
Yes the API take a json string. Let's say for creating a booking:

```json
{
    "flow": "API",
    "source": 1,
    "interactive": "0",
    "return_url": "http://www.mysite.com/return.php",
    "mandate": true,
    "mandate_currency": "EUR",
    "customer": {
        "firstname": "John",
        "lastname": "Doe",
        "email": "test@domain.com",
        "language": "en"
    },
    "payment_method": {
        "type" : "CREDITCARD",
        "number" : 4111111111111111,
        "cardholder": "Card Holder Name",
        "exp_month": "01",
        "exp_year": "2016",
        "cvc": "123"
    }
}
```

As there are lot of parameters, a method like `Booking->create($flow, $source, $interactive, $returnUrl,  $mandate, $mandateCurrency, $customer, $paymentMethod)` wouldn't be acceptable. So let's wrap them in a DTO that we can name CreateBookingRequest. We have now: `Booking->create($createBookingRequest)` which looks better.

But now to make the request:
`$response = $this->httpPost('/v1/bookings/new', $params);`

We need to convert our $createBookingRequest to $params

I think the client should integrate a serializer to allow to pass an object to a request. It's the case for the deserialization from a response, why it wouldn't be the case for a serialization to a request? 

To avoid additional dependencies, I think it's better to create a serializer (like you did for the deserializer). Would you have some directions to do it?

**Comment by Kwadz** [comment]
I just realized that unlike the JMSSerializer, the SymfonySerializer do not need other dependencies: https://packagist.org/packages/symfony/serializer
Why don't you use it for the deserialization? It would avoid creating specific `DomainEntity::create()` method for each entity, no? And at the same time it would allow the serialization to the request.
Do you think that is a good idea?

I also found a method from PHP >= 5.4: http://php.net/manual/fr/jsonserializable.jsonserialize.php,
but this allows serialization only (no deserialization).

**Comment by sagikazarmark** [comment]
In more complicated cases using a separate serialization layer might be the way to go, but in simple cases json_decode might be enough.

**Comment by Kwadz** [comment]
With `json_encode()` a piece of serializer already exists:
`HttpApi::createJsonBody(array $parameters)`

We would just need to pass an object which implements [JsonSerializable](http://www.php.net/manual/en/class.jsonserializable.php).

However, as there is no overloading in PHP, what could be a clean way to add
`HttpApi::createJsonBody(\JsonSerializable $obj)`?

Same problem with the current `HttpApi::httpPost($path, array $parameters = [], array $requestHeaders = [])`

**Comment by sagikazarmark** [comment]
Will be resolved in #32

**Comment by Kwadz** [comment]
What do you think about wrapping parameters in request objects specific to the client like:

```php
class TweetRequest implements \JsonSerializable
{

    private $message;
    private $hashtag;
    private $nestedObject;
    // ...
}
```

and add methods in HttpApi:

```php
protected function httpPostObject($path, $object, array $requestHeaders = [])
{
    $json = $this->createJsonBodyFromObject($object);
    return $this->httpPostRaw($path, $json, $requestHeaders);
}

protected function createJsonBodyFromObject($request)
{     
    return (is_null($request)) ? null : json_encode($request);
}
```

This would avoid creating a specific Builder method for each case. Why the current way that you offer would be preferable?

**Comment by Nyholm** [comment]
If a majority of your API endpoints requires complex param structure, I think your approach is valid. But I do not think it is for the general case.
