### ISSUE TITLE
Code factorization for errors handling

### ISSUE THREAD

**Issue by Kwadz** [api-php/boilerplate#68]
I noticed we use the following piece of code in the `FAPI\Boilerplate\Api\Tweet` class.

```
        // Use any valid status code here
        if ($response->getStatusCode() !== 201) {
            switch ($response->getStatusCode()) {
                case 400:
                    throw new DomainExceptions\ValidationException();
                    break;
                default:
                    $this->handleErrors($response);
                    break;
            }
        }
```

If we assume that other classes like `Tweet` will be created, do you think that this could be factorized in a function for every request type (get, create, update, delete)?

**Comment by sagikazarmark** [comment]
Different calls can have different errors, but a class level error handler which contains all the common cases should work.
